(()=>{'use strict';
const header=document.getElementById('header');
const progress=document.getElementById('progress');
const menu=document.getElementById('menu');
const mobile=document.getElementById('mobileMenu');
const updateScroll=()=>{const y=window.scrollY;const max=Math.max(document.documentElement.scrollHeight-innerHeight,1);header.classList.toggle('scrolled',y>18);progress.style.transform=`scaleX(${Math.min(y/max,1)})`};
updateScroll();addEventListener('scroll',updateScroll,{passive:true});
menu.addEventListener('click',()=>{const open=mobile.classList.toggle('open');menu.classList.toggle('open',open);menu.setAttribute('aria-expanded',open);mobile.setAttribute('aria-hidden',!open)});
mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false');mobile.setAttribute('aria-hidden','true')}));
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const rail=document.getElementById('rail');const shift=()=>Math.min(rail.clientWidth*.82,760);document.getElementById('prev').addEventListener('click',()=>rail.scrollBy({left:-shift(),behavior:'smooth'}));document.getElementById('next').addEventListener('click',()=>rail.scrollBy({left:shift(),behavior:'smooth'}));
const speed=document.getElementById('speed'),battery=document.getElementById('battery'),range=document.getElementById('range'),regen=document.getElementById('regen'),power=document.getElementById('power');
const states={road:['084','78%','214 км','MID','62%'],attack:['146','61%','128 км','LOW','94%'],range:['062','84%','286 км','HIGH','42%']};
document.querySelectorAll('.modes button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.modes button').forEach(x=>{const active=x===btn;x.classList.toggle('active',active);x.setAttribute('aria-pressed',active)});const s=states[btn.dataset.mode];speed.textContent=s[0];battery.textContent=s[1];range.textContent=s[2];regen.textContent=s[3];power.style.width=s[4]}));
const clock=document.getElementById('clock');const tick=()=>clock.textContent=new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});tick();setInterval(tick,15000);
const stage=document.getElementById('stage'),activateBtn=document.getElementById('activateBtn'),status=document.getElementById('bootStatus'),note=document.getElementById('activateNote');
activateBtn.addEventListener('click',()=>{const on=stage.classList.toggle('stage-live');status.textContent=on?'SYSTEM ACTIVE':'STANDBY';activateBtn.querySelector('span').textContent=on?'ОТКЛЮЧИТЬ DEMO':'АКТИВИРОВАТЬ R1';note.textContent=on?'Оптика и бортовая система активированы. Можно менять цветовой режим.':'Система ожидает запуска.'});
document.querySelectorAll('.sw').forEach(sw=>sw.addEventListener('click',()=>{document.querySelectorAll('.sw').forEach(x=>{const active=x===sw;x.classList.toggle('active',active);x.setAttribute('aria-pressed',active)});stage.classList.remove('color-ice','color-stealth');if(sw.dataset.color==='ice')stage.classList.add('color-ice');if(sw.dataset.color==='stealth')stage.classList.add('color-stealth')}));
})();